## DOCS
[KAFKA REST](https://docs.confluent.io/cloud/current/kafka-rest/kafka-rest-cc.html)
[CLOUD METRICS](https://docs.confluent.io/cloud/current/monitoring/metrics-api.html)
[METRICS DATASETS](https://api.telemetry.confluent.cloud/docs/descriptors/datasets/cloud)
https://api.telemetry.confluent.cloud/docs

#################################
### KAFKA V3 API
#################################
### CONFIGURATION / VARIABLES (.env)

@kafka_rest = {{$dotenv KAFKA_REST}}
@kafka_cluster_id = {{$dotenv KAFKA_CLUSTER_ID}}
@kafka_api_key = {{$dotenv KAFKA_API_KEY}}
@kafka_api_secret = {{$dotenv KAFKA_API_SECRET}}

### LIST TOPICS - REST API
# @name topics_list
GET {{kafka_rest}}/kafka/v3/clusters/{{kafka_cluster_id}}/topics
Authorization: Basic {{kafka_api_key}}:{{kafka_api_secret}}

###
@commentId = {{topics_list.response.body.$.data[*].topic_name}}
# '.data[].topic_name'

### CONSUMERS - REST API
# @name consumer_groups
GET {{kafka_rest}}/kafka/v3/clusters/{{kafka_cluster_id}}/consumer-groups
Authorization: Basic {{kafka_api_key}}:{{kafka_api_secret}}

###
@group_id = {{consumer_groups.response.body.$.data[*].consumer_group_id}}

### CONSUMERS2 - REST API
GET {{kafka_rest}}/kafka/v3/clusters/{{kafka_cluster_id}}/consumer-groups/{{group_id}}/consumers
Authorization: Basic {{kafka_api_key}}:{{kafka_api_secret}}




#################################
### METRICS API - Confluent Cloud
#################################
### CONFIGURATION / VARIABLES (.env)

@metrics_endpoint = {{$dotenv METRICS_API_ENDPOINT}}
@metrics_api_key = {{$dotenv CLOUD_API_KEY}}
@metrics_api_secret = {{$dotenv CLOUD_API_SECRET}}

### METRICS AVAILABLE RESOURCES
GET {{metrics_endpoint}}/descriptors/resources
Authorization: Basic {{metrics_api_key}}:{{metrics_api_secret}}
Content-Type: application/json  

### AVAILABLE METRICS
GET {{metrics_endpoint}}/descriptors/metrics?resource_type=kafka
Authorization: Basic {{metrics_api_key}}:{{metrics_api_secret}}
Content-Type: application/json


### LIST TOPICS - METRICS API - INTERVAL 1H, Granulary 1M, Group by topic
POST {{metrics_endpoint}}/query
Authorization: Basic {{metrics_api_key}}:{{metrics_api_secret}}
Content-Type: application/json  

{
  "aggregations": [{"metric": "io.confluent.kafka.server/received_bytes"}],
  "filter": {"field": "resource.kafka.id", "op": "EQ", "value": "{{kafka_cluster_id}}"},
  "granularity": "PT1M",
  "group_by": ["metric.topic"],
  "intervals": ["now-1h/now"],
  "limit": 1000
}

### Specific topic - METRICS API - INTERVAL 30D, Granulary 1D, Group by topic
POST {{metrics_endpoint}}/query
Authorization: Basic {{metrics_api_key}}:{{metrics_api_secret}}
Content-Type: application/json  

{
  "aggregations": [{"metric": "io.confluent.kafka.server/received_bytes"}],
  "filter": {"field": "resource.kafka.id", "op": "EQ", "value": "{{kafka_cluster_id}}"},
  "granularity": "P1D",
  "group_by": ["metric.topic"],
  "intervals": ["now-30d/now-8d"],
  "limit": 1000
}

### LIST TOPICS - DISCOVERY EXPORT
GET {{metrics_endpoint}}/discovery
Authorization: Basic {{metrics_api_key}}:{{metrics_api_secret}}
Content-Type: application/json  

### LIST TOPICS - EXPORT
GET {{metrics_endpoint}}/export?resource.kafka.id={{kafka_cluster_id}}
Authorization: Basic {{metrics_api_key}}:{{metrics_api_secret}}
Content-Type: application/json  




#################################
### CATALOG API - Schema Registry
#################################
### CONFIGURATION / VARIABLES (.env)

@catalog_endpoint = {{$dotenv CATALOG_ENDPOINT}}
@catalog_api_key = {{$dotenv CATALOG_API_KEY}}
@catalog_api_secret = {{$dotenv CATALOG_API_SECRET}}

### TOPIC METADATA - jq '.entity.attributes | {name, qualifiedName, owner, ownerEmail}'

GET {{catalog_endpoint}}/catalog/v1/entity/type/kafka_topic/name/{{kafka_cluster_id}}:abc
Authorization: Basic {{catalog_api_key}}:{{catalog_api_secret}}
Content-Type: application/json

### PUT to change the topic Owner and EmailAddress
PUT {{catalog_endpoint}}/catalog/v1/entity
Authorization: Basic {{catalog_api_key}}:{{catalog_api_secret}}
Content-Type: application/json

{
  "entity": {
    "typeName": "kafka_topic",
    "attributes": {
      "qualifiedName": "{{kafka_cluster_id}}:abc",
      "owner": "Dennis Federico",
      "ownerEmail": "dfederico@company.com"
    }
  }
}


### USAGE BY PRINCIPAL - METRICS API - INTERVAL 7D, Granulary 1M, Group by principal_id

  ### PRODUCERS

  curl --silent -X POST "https://api.telemetry.confluent.cloud/v2/metrics/cloud/query" \
  -H "Content-Type: application/json" \
  -H "Authorization: Basic <BASE64(cloud_api_key:cloud_api_secret)>" \
  -d '{
    "aggregations": [{"metric": "io.confluent.kafka.server/received_bytes"}],
    "filter": {"field": "resource.kafka.id", "op": "EQ", "value": "lkc-XXXXX"},
    "granularity": "PT1M",
    "group_by": ["metric.principal_id"],
    "intervals": ["now-5m/now"],
    "limit": 1000
  }' | jq -r '.data[].metric.principal_id' | sort -u


  ### CONSUMERS

  curl --silent -X POST "https://api.telemetry.confluent.cloud/v2/metrics/cloud/query" \
  -H "Content-Type: "application/json" \
  -H "Authorization: Basic <BASE64(cloud_api_key:cloud_api_secret)>" \
  -d '{
    "aggregations": [{"metric": "io.confluent.kafka.server/sent_bytes"}],
    "filter": {"field": "resource.kafka.id", "op": "EQ", "value": "lkc-XXXXX"},
    "granularity": "PT1M",
    "group_by": ["metric.principal_id"],
    "intervals": ["now-5m/now"],
    "limit": 1000
  }' | jq -r '.data[].metric.principal_id' | sort -u
